### ISSUE TITLE
Add normal getty instead of cttyhack

### ISSUE THREAD

**Issue by protonesso** [AwlsomeAlex/stelalinux#3]
Why not? Also you can just type "root" and press enter and it let you to command prompt without password!

**Comment by protonesso** [comment]
Until you set the password ;)

**Comment by AwlsomeAlex** [comment]
That's a very good point. I'll implement that tomorrow! @protonesso

**Comment by AwlsomeAlex** [comment]
@protonesso Commit b647525 should fulfill this.

**Comment by protonesso** [comment]
http://clfs.org/view/clfs-embedded/x86/bootscripts/inittab.html

**Comment by AwlsomeAlex** [comment]
@protonesso Should be implemented with 341bc67 now.
