### ISSUE TITLE
Need Toolchain

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/stelalinux#6]
I'm trying to setup vim to be compiled, but for some reason it keeps telling me:
`checking whether the C compiler works... no

configure: error: in /home/awlsomealex/Git/stelalinux/work/vim/vim-8.1.2424/src:

configure: error: C compiler cannot create executables`
Did I do something wrong in my build script @protonesso ? I've been fighting this for close to an hour and don't see anything out of line.....

**Comment by AwlsomeAlex** [comment]
Okay so I fixed a few things, but now I get this
`checking --with-tlib argument... ncurses
checking for linking with ncurses library... configure: error: FAILED`
Just saying, I have libncurses-dev downloaded.

**Comment by AwlsomeAlex** [comment]
I'm at this point.
`/home/awlsomealex/Git/stelalinux/toolchain/bin/../lib/gcc/x86_64-linux-musl     /9.2.1/../../../../x86_64-linux-musl/bin/ld: warning: libdl.so.2, needed by      /usr/lib/x86_64-linux-gnu/libncurses.so.6, not found (try using -rpath or      -rpath-link)`

**Comment by protonesso** [comment]
I'd recommend to build your own cross-toolchain from scratch including file, pkgconf, gcc, binutils, musl and linux-headers

**Comment by AwlsomeAlex** [comment]
@protonesso I've talked to the musl.cc developer about doing something like that before. When I get more time (and resources) to heavily look into that, I'll create a musl toolchain, or even create a musl chroot to act as a native build. But for now, I'm going to experiment with glibc.

**Comment by AwlsomeAlex** [comment]
@protonesso `configure:14208: error: possibly undefined macro: AX_PTHREAD` when trying to build gcc-static
